name: things
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  slang: ^4.12.0
  slang_flutter: ^4.12.0
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.8
  intl: ^0.20.2
  go_router: ^17.1.0
  injectable: ^2.7.1+4
  get_it: ^9.2.0
  firebase_core: ^4.4.0
  firebase_ai: ^3.8.0
  characters: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  slang_build_runner: ^4.12.0
  drift_dev: ^2.30.1
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  go_router_builder: ^4.1.3
  injectable_generator: ^2.9.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope.ttf
